addons:
  firefox: latest-unsigned
  
language: python

python:
  - "3.6"

env:
  -DJANGO=2.0 DB=sqlite

install:
  - pip install pipenv
  - pipenv install


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - pipenv run python manage.py collectstatic --noinput
  - pipenv run python manage.py test --settings=bugheist.settings

notifications:
  slack: owasp:Ly2aPB4oB9U05W6BLDAl8oM8