addons:
  firefox: "49.0.2"
  
language: python

python:
  - "3.6"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

env:
  -DJANGO=2.0 DB=sqlite

services:
  - xvfb

install:
  - pip install pipenv
  - pipenv install

before_script:
  - "export DISPLAY=:99.0"

script:
  - pipenv run python manage.py collectstatic --noinput
  - pipenv run python manage.py test --settings=bugheist.settings
