version: "3"

services:
  app:
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    build: .
    volumes:
      - .:/blt
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SENTRY_DSN=${SENTRY_DSN}
