name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: 1

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: write
  # Note: Adjust the permissions above as necessary. The 'contents: read' permission is typically required for CodeQL analysis.

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11.2
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  code-ql:
    name: Run CodeQL
    needs: pre-commit
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language:
          - 'javascript'
          - 'python'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  test:
    name: Run Tests
    needs: code-ql
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
          cache: 'poetry'
      - name: Install dependencies
        run: pip install poetry && poetry install
      - name: Collect static files
        run: poetry run python manage.py collectstatic --noinput
      - name: Run tests
        run: poetry run xvfb-run --auto-servernum python manage.py test -v 3 --failfast
