name: Django Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: nanasess/setup-chromedriver@v1
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pipenv'

#     - name: sudo apt-get update
#       run: sudo apt-get update
    - name: sudo apt-get install -y --no-install-recommends libmemcached-dev xvfb
      run: sudo apt-get install -y --no-install-recommends libmemcached-dev xvfb
    - name: pipenv install
      run: pipenv install
    - name: pipenv run python manage.py migrate
      run: pipenv run python manage.py migrate
    - name: pipenv run python manage.py collectstatic --noinput
      run: pipenv run python manage.py collectstatic --noinput
    - name: xvfb-run --auto-servernum pipenv run python manage.py test
      run: xvfb-run --auto-servernum pipenv run python manage.py test
