name: Slash assign

on:
  schedule:
    - cron: '* * * * *'
  issue_comment:
    types: [created]

jobs:
  slash_assign:
    # If the acton was triggered by a new comment that starts with `/assign`
    # or a on a schedule
    if: >
      (github.event_name == 'issue_comment' && (
      startsWith(github.event.comment.body, '/assign') || 
      contains(github.event.comment.body, 'assign to me') || 
      contains(github.event.comment.body, 'please assign me this')  || 
      contains(github.event.comment.body, 'assign this to me')  || 
      contains(github.event.comment.body, 'I can try fixing this')  || 
      contains(github.event.comment.body, 'i am interested in doing this')  || 
      contains(github.event.comment.body, 'I am interested in contributing'))) || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Check out GitHub Action
        uses: actions/checkout@v2
        with:
          repository: Bugheist/slash-assign-action
          ref: main
          path: .github/actions/slash-assign-action
      - name: Compile the Action
        run: |
          npm install
          npm run build
        working-directory: .github/actions/slash-assign-action

      - name: Assign the user or unassign stale assignments
        uses: ./.github/actions/slash-assign-action
