name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres:10.8
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: github_actions
#         ports:
#           - 5432:5432
#         # needed because the postgres container does not provide a healthcheck
#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: browser-actions/setup-geckodriver@latest
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv wheel
        pipenv install

    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test
